### ISSUE TITLE
ApplicationRecord

### ISSUE THREAD

**Issue by MichaelSp** [reactrb/reactive-record#8]
In Rails 5 Models suppose to derive from ApplicationModel. But that constant is not defined in reactive-record:

```
V8::Error - uninitialized constant ApplicationRecord:
  therubyracer (0.12.2) lib/v8/error.rb:86:in `block in try'
  therubyracer (0.12.2) lib/v8/error.rb:83:in `try'
  therubyracer (0.12.2) lib/v8/context.rb:99:in `block in eval'
  therubyracer (0.12.2) lib/v8/context.rb:248:in `block (2 levels) in lock_scope_and_enter'
  therubyracer (0.12.2) lib/v8/context.rb:245:in `block in lock_scope_and_enter'
  therubyracer (0.12.2) lib/v8/context.rb:244:in `lock_scope_and_enter'
  therubyracer (0.12.2) lib/v8/context.rb:204:in `enter'
  therubyracer (0.12.2) lib/v8/context.rb:94:in `eval'
  reactrb (0.9.0) lib/reactive-ruby/component_loader.rb:15:in `load'
```

Add hint in the docs to create that `ApplicationRecord` in the `models/plublic`-folder

**Comment by catmando** [comment]
Good idea.  I thought there was something!  Would u consider updating the docs and submit a PR?

**Comment by catmando** [comment]
@michael - I feel like an idiot... I did not realize that you were looking at a deprecated version of this gem.  Checkout https://github.com/ruby-hyperloop/hyper-mesh

**Comment by MichaelSp** [comment]
Oh nice! Already using it. But I started my journey with this gem. So maybe time for a big "DEPRECATION" warning in the Readme?

**Comment by catmando** [comment]
Yeah I thought there was one... On it right NOW!
